services:
  - type: web
    name: gemini-api-render
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn analyze:app
    envVars:
      - key: GEMINI_API_KEY
        value: TU_CLAVE_API_DE_GEMINI
